core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    # PaymentView,
    # AddCouponView,
    RequestRefundView,
    CategoryView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    # path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
        name='remove-single-item-from-cart'),
    # path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

demo/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from demo import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path('', include('core.urls', namespace='core')),
    path("", include("apps.home.urls")),
    
    # url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar">
  {% include "header.html" %}

  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %} {% endblock %}
  <style type="text/css">
    .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
  </style>
  <body class="animsition">
    {% include "nav.html"%}
    <div class="mt-2">
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}

        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>

    {% endfor %} 
    {% endif %} 

    {% block content %} 
    {% endblock content %}

    {% block extra_body %} 
    {% endblock %} 

    {% include "footer.html"%} 
    {% include "script.html"%}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
  </body>
</html>

templates/checkout.html
{% extends 'base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}

{% block content %}


  {% comment %} <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  </style>
} {% endcomment %}


  

<div class="container">
  <div class="py-5 text-center">
    <img class="d-block mx-auto mb-4" src="{% static 'images/icons/2.png' %}" alt="" width="100" height="100">
      <p style="color: black; "><b style="font-size: 32px;">	واجهة بيانات عنوان توصيل الطلبية   </b></p>
    <p > </p>
    <p class="lead">   بيانات عنوان الزبون لأستلام الطلبية المطلوبة </p>
  </div>

  {% comment %} <div class="row"> {% endcomment %}


    <div  class="t-center p-l-15 p-r-15 card" >
      <h4 class="mb-3 text-center" style="margin-top: 26px;">عنوان توصيل الطلبية</h4>
      <form  style="margin-bottom: 26px;"  dir='RTL'  method="POST" class="needs-validation" >
        {% csrf_token %}  
        <div class="mb-3 text-right">
          <label for="street_address">العنوان</label>
          {{ form.street_address }}
          <div class="invalid-feedback">
            الرجاء كتابة العنوان مطلوب.
          </div>
        </div>

        <div class="mb-3 text-right">
          <label for="apartment_address">العنوان 2 <span class="text-muted">(اختياري)</span></label>
          {{ form.apartment_address }}
        </div>

        <div class="row">
          <div class="col-md-5 mb-3 text-right">
            <label for="country">الدولة</label>
            {{ form.country }}
            <div class="invalid-feedback">
              الرجاء تحديد دولة صالحة.
            </div>
          </div>
          <div class="col-md-4 mb-3 text-right">
            <label for="city">المدينة</label>
            {{ form.city }}
            <div class="invalid-feedback">
              اسم المدينة مطلوب.
            </div>
          </div>
          <div class="col-md-3 mb-3 text-right">
            <label for="phone">رقم الهاتف </label>
            {{ form.phone }}
            <div class="invalid-feedback">
              رقم الهاتف مطلوب.
            </div>
          </div>
        </div>
        <hr class="mb-4">
        {% comment %} <div class="custom-control custom-checkbox"> {% endcomment %}
          {% comment %} <input {% if form.same_shipping_address.value %}checked{% endif %} type="checkbox" class="custom-control-input" id="same_shipping_address"> {% endcomment %}
          
          {% comment %} <label class="custom-control-label" for="same_shipping_address">عنوان التوصيل هو نفسه عنوان إرسال الطلبية الخاص بي.</label> {% endcomment %}
        {% comment %} </div> {% endcomment %}
        
        <div class="col-md-4 mb-2 text-right">
          <label for="gps"> احداثيات الموقع </label>
          {{ form.gps }}
          {% comment %} <div class="invalid-feedback"> {% endcomment %}
            {% comment %} احداثيات الموقع مطلوب. {% endcomment %}
          {% comment %} </div> {% endcomment %}
        </div>
        <div  class="col-md-5 text-right">
          {% comment %} <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input" id="save-info"> {% endcomment %}
          {{ form.save_info }}
          <label  >احفظ هذه المعلومات في المرة القادمة</label>
        </div>
      
        {% comment %} <hr class="mb-4"> {% endcomment %}

        {% comment %} <h4 class="mb-3">دفع</h4> {% endcomment %}

        {% comment %} <div class="d-block my-3">
        {% for value, name in form.fields.address_type.choices %}
          <div class="custom-control custom-radio">
            <input id="{{ name }}" name="address_type" value="{{ value }}" type="radio" class="custom-control-input"  required>
            <label class="custom-control-label" for="{{name}}">{{ name }}</label>
          </div>
          {% endfor %}
          <hr class="mb-4">
        </div> {% endcomment %}
        
        <button style="margin-bottom: 26px;" class="btn btn-primary btn-lg" type="submit">  تاكيد حفظ الطلبية </button>
      </form>
    </div>

    {% comment %} {% include "order_snippet.html" %} {% endcomment %}



  {% comment %} <footer class="my-5 pt-5 text-muted text-center text-small">
    {% comment %} <p class="mb-1">&copy; 2022-1444 موقع الكتروني للتسويق</p> {% endcomment %}
    {% comment %} <ul class="list-inline">
      <li class="list-inline-item"><a href="#">خصوصية</a></li>
      <li class="list-inline-item"><a href="#">شروط</a></li>
      <li class="list-inline-item"><a href="#">الدعم</a></li>
    </ul>
  </footer>   {% endcomment %}
</div>
{% endblock content %}

templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background-color: white;
		color: black !important;
	}
	.topbar a:hover{
		color: black;
	}
</style>
<!-- Header -->
<header lang="ar" dir="rtl"   class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			
			<div class="topbar">
				<a href="/" class="header-wrapicon1 dis-block">
					<p style="color: black; "><b style="font-size: 22px;">	رياح المحيط   </b>اول سوق الكتروني في اليمن لبيع الاجهزة الطبية</p>
						{% comment %} D</b>JANGO SHOP</p> {% endcomment %}
				</a>
					<span class="linedivide1"></span>
				<a href="/"  class="topbar-email">
					<img src="{% static 'images/icons/logo.png' %}" alt="IMG-LOGO">
				</a>
				<span class="linedivide1"></span>
				<span class="topbar-child1">
					{% comment %} شحن مجاني للطلبات القياسية التي تزيد عن دولار {% endcomment %}
					<div class="topbar">
						<a href="#" class="topbar-social-item fab fa-facebook"></a>
						<a href="#" class="topbar-social-item fab fa-instagram"></a>
						<a href="#" class="topbar-social-item fab fa-pinterest-p"></a>
						<a href="#" class="topbar-social-item fab fa-twitter"></a>
						<a href="#" class="topbar-social-item fab fa-youtube"></a>
					</div>
					
				</span>
				
				<div  class="logo">
					<span class="topbar-email">
							<a href="{% url 'logout' %}" class="header-wrapicon1 dis-block">
								{% if request.user.username %}
								<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
								{{ request.user.username }} - تسجيل الخروج
								{% endif  %} 
							</a>
					</span>
					
					{% comment %} <div class="topbar-language rs1-select2">
						<select class="selection-1" name="time">
							<option>دولار</option>
							<option>ريال يمني</option>
						</select>
					</div> {% endcomment %}
				</div>
			</div>

			<div  class="wrap_header">
				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
							<li>
								<a href="/">الصفحة الرئيسية</a>
							</li>
							<li>
								<a href="/shop/">التسوق</a>
							</li>
							{% categories %}
							{% if request.user.is_authenticated %}
							<li>
								<a href="{% url 'core:order-summary' %}">
								<img src="{% static 'images/icons/icon-header-022.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
								عربة التسوق<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
							</li>
							{% comment %} <li>
								<a href="{% url 'logout' %}">تسجيل الخروج</a>
							</li> {% endcomment %}
							{% comment %} <li class="nav-item">
								<a class="nav-link" aria-current="page" href="{% url 'department-page' %}">Departments</a>
							</li> {% endcomment %}
							{% else %}
							<li>
								<a href="#">تسجيل الدخول</a>
								<ul class="sub_menu">
									<li><a href="{% url 'login' %}">تسجيل الدخول</a></li>
									<li><a class="nav-link " href="{% url 'register' %}">تسجيل مستخدم جديد</a></li>
								</ul>
							</li>
							{% endif %}
						</ul>
					</nav>
				</div>

				<!-- Header Icon -->
				<div class="header-icons">
					{% comment %} <a href="#" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">

					</a>
					
					{% endcomment %}
						<!-- Logo -->

					{% comment %} <span class="linedivide1"></span> {% endcomment %}

					{% comment %} <div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">0</span>

						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											قميص أبيض مع تفاصيل طيات الظهر
										</a>

										<span class="header-cart-item-info">
											1 x $19.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											التحويل المظهر الى اللون الاسودConverse All Star Hi Black Canvas
										</a>

										<span class="header-cart-item-info">
											1 x $39.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Nixon Porter Leather Watch In Tan
										</a>

										<span class="header-cart-item-info">
											1 x $17.00
										</span>
									</div>
								</li>
							</ul>

							<div class="header-cart-total">
								الاجمالي: $75.00
							</div>

							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="{% url 'core:order-summary' %}" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										عرض عربة التسوق
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="checkout" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										الدفع
									</a>
								</div>
							</div>
						</div>
					</div> {% endcomment %}
				</div>
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="/" class="logo-mobile">
				<img src="{% static 'images/icons/logo.png' %}" alt="IMG-LOGO">
			</a>

			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">

						<a href="{% url 'logout' %}" class="header-wrapicon1 dis-block">
							{% if request.user.username %}
							<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
							{{ request.user.username }} - تسجيل الخروج
							{% endif  %} 
						</a>


					<span class="linedivide2"></span>

					{% comment %} <div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">0</span>

						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											قميص مع تفاصيل طيات الظهر
										</a>

										<span class="header-cart-item-info">
											1 x $19.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											التحويل المظهر الى اللون الاسود Converse All Star Hi Black Canvas
										</a>

										<span class="header-cart-item-info">
											1 x $39.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Nixon Porter Leather Watch In Tan
										</a>

										<span class="header-cart-item-info">
											1 x $17.00
										</span>
									</div>
								</li>
							</ul>

							<div class="header-cart-total">
								الاجمالي: $75.00
							</div>

							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="{% url 'core:order-summary' %}" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										عرض عربة التسوق
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="checkout" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										الدفع
									</a>
								</div>
							</div>
						</div>
					</div> {% endcomment %}
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<span class="topbar-child1">
							<p style="color: black; "><b style="font-size: 22px;">	رياح المحيط   </b>اول سوق الكتروني في اليمن لبيع الاجهزة الطبية</p>
						</span>
					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">


							{% comment %} <div class="topbar-language rs1-select2">
								<select class="selection-1" name="time">
									<option>دولار</option>
									<option>ريال يمني</option>
								</select>
							</div> {% endcomment %}
						</div>
					</li>

					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="/">الصفحة الرئيسية</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">تسوق</a>
					</li>

					{% categories_mobile %}

					{% if request.user.is_authenticated %}
					<li class="item-menu-mobile">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<a href="{% url 'core:order-summary' %}">عربة التسوق<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
					</li>
					<li class="item-menu-mobile">
						<a href="{% url 'logout' %}">تسجيل الخروج</a>
					</li>
					{% else %}
					<li class="item-menu-mobile">
						<a href="#">تسجيل الدخول</a>
						<ul class="sub-menu">
							<li><a href="{% url 'login' %}">تسجيل الدخول</a></li>
							<li><a class="nav-link " href="{% url 'register' %}"> تسجيل مستخدم جديد</a></li>
						</ul>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>
					{% endif %}

				</ul>
			</nav>
		</div>
	</header>

templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2 style="margin-top: 26px; margin-bottom: 26px;"  class="text-center">ملخص قائمة الطلبات</h2>
      <div dir='rtl' class="container-table-cart pos-relative">
        <div dir='rtl' class="wrap-table-shopping-cart bgwhite">
          <table dir='rtl' class="table">
            <thead> 
              <tr class="table-head  text-center">
                <th  class="column-1" scope="col">م</th>
                <th class="column-2" scope="col">الصورة</th>
                <th class="column-3" scope="col">اسم المنتج</th>
                <th class="column-4" scope="col">السعر</th>
                <th class="column-5 p-l-70" scope="col">الكمية</th>
                <th class="column-6" scope="col">الحجم</th>
                <th class="column-7" scope="col">اجمالي السعر</th>
              </tr>
            </thead>
            <tbody  class="text-center">
              {% for order_item in object.items.all %}
                <tr>
                <th scope="row">{{ forloop.counter }}</th>
                  <td>
			              <img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
                  </td>
                  <td>{{ order_item.item.title }}</td>
                <td>{{ order_item.item.price }}</td>
                <td>
            	    <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
            	    {{ order_item.quantity }}
                  {% comment %} <a href=""  onclick="this.href='{% url 'core:add-to-cart' order_item.item.slug %}?sizeItemss=${order_item.sizeItem}'" class="btn btn-primary" style="margin: 2px;">أضف إلى عربة التسوق</a> {% endcomment %}
            	    {% if order_item.sizeItem%}
                  <a href=""  onclick="this.href='{% url 'core:add-to-cart' order_item.item.slug %}?sizeItemss={{ order_item.sizeItem.id }}'" ><i class="fas fa-plus ml-3"></i></a>
                  {% else %}
                  <a href="{% url 'core:add-to-cart' order_item.item.slug %}" ><i class="fas fa-plus ml-3"></i></a>
                  {% endif %}
                  
                  
                </td>
                <td>
                  <div class="rs2-select2 rs3-select2 w-size16">
                    {% comment %} <select class="custom-select custom-select-sm"> {% endcomment %}
                      {% comment %} <option>إختر من القائمة</option>
                      {% for size in order_item.get_sizeItem %}
                          <option value="{{ size.id }}" {% if order_item.sizeItem.id == size.id %} selected  {% endif %}>{{ size }}</option>
                      {% endfor %}
                    </select> {% endcomment %}

                    {{ order_item.sizeItem }}

                    {% comment %} <select class="form-control" name="size" select={{ order_item.sizeItem }} value={{ order_item.sizeItem }}>
                      <option>إختر من القائمة</option>
                      {% for id, name in form.fields.assigned_employee.choices %}
                        <option value="{{ id }}"{% if form.fields.assigned_employee.value == id %} selected{% endif %}>{{ name }}</option>
                      {% endfor %}


                      {% for sizeItem  in order_item.get_sizeItem %}
                        <option>{{ sizeItem }}</option>
                      {% endfor %}
                    </select> {% endcomment %}
                  </div>
                  
                  
                  {% comment %} {{ order_item.get_sizeItem }} {% endcomment %}
                </td>
                <td>
                  {% if order_item.item.discount_price %}
                    ${{ order_item.get_total_discount_item_price}}
                    <span class="badge badge-primary">  الخصم المكتسب ${{ order_item.get_amount_saved }}</span>
                  {% else %}
                    ${{ order_item.get_total_item_price}}
                  {% endif %}
                </td>
                <td>
                  <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                    <i class="fas fa-trash float-right"></i>
                  </a>
                </td>
              </tr>
              {% empty %}
              <tr>
			          <td colspan="5">عربة التسوق فارغة</td>
              </tr>
            </tbody>
            {% endfor %}
            {% comment %} {% if object.coupon %}
              <tr>
                <td colspan="5"><b>قسيمة : </b></td>
                <td>- ${{ object.coupon.amount }}</td>
              </tr>
            {% endif%} {% endcomment %}
            {% if object.get_total %}
              <tr>
        	      <td colspan="5"><b>اجمالي الطلب الكلي:    {{ object.get_total }} $</b></td>
              </tr>
              <tr>
        	      <td colspan="5">
        		      <a href="/checkout" class="btn btn-warning float-right ml-2">تاكيد الطلب</a>
        		      <a href="/" class="btn btn-primary float-right">مواصلة التسوق</a>
        	      </td>
              </tr>
            {% endif %}
          </table>
        </div>
      </div>
    </div>
  </div>
</div>





{% endblock content %}

templates/request_refund.html
{% extends 'base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-3 mt-3">
      <h2>طلب استرداد</h2>
      <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">ارسال</button>
      </form>
     
    </div>
  </div>
</div>

{% endblock content %}